config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :thofins

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :thofins
end

app/models/thofin.rb
class Thofin < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  
  has_and_belongs_to_many :tags, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/thofins_controller.rb
class ThofinsController < ApplicationController
  before_action :set_thofin, only: [:show, :edit, :update, :destroy]

  # GET /thofins
  # GET /thofins.json
  def index
    @thofins = Thofin.all
  end

  # GET /thofins/1
  # GET /thofins/1.json
  def show
  end

  # GET /thofins/new
  def new
    @thofin = Thofin.new
  end

  # GET /thofins/1/edit
  def edit
  end

  # POST /thofins
  # POST /thofins.json
  def create
    @thofin = Thofin.new(thofin_params)

    respond_to do |format|
      if @thofin.save
        format.html { redirect_to @thofin, notice: 'Thofin was successfully created.' }
        format.json { render :show, status: :created, location: @thofin }
      else
        format.html { render :new }
        format.json { render json: @thofin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thofins/1
  # PATCH/PUT /thofins/1.json
  def update
    respond_to do |format|
      if @thofin.update(thofin_params)
        format.html { redirect_to @thofin, notice: 'Thofin was successfully updated.' }
        format.json { render :show, status: :ok, location: @thofin }
      else
        format.html { render :edit }
        format.json { render json: @thofin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thofins/1
  # DELETE /thofins/1.json
  def destroy
    @thofin.destroy
    respond_to do |format|
      format.html { redirect_to thofins_url, notice: 'Thofin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thofin
      @thofin = Thofin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thofin_params
      params.require(:thofin).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/thofins_helper.rb
module ThofinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyinthDS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<%= render 'shared/navigation' %>
    
	<div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-3">
          <h3>?</h3>
        </div>
        <div class="col-xs-9">
          <%= yield %>
        </div>
      </div>
    </div>

</body>
</html>

app/views/shared/_navigation.html.erb
<!-- app/views/shared/_navigation.html.erb -->

<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Tealeaf Tags</a>
    </div>
  </div>
</nav>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'View list', tags_path %></li>
  <li><%= link_to 'New tag', new_tag_path %></li>
</ul>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_tag_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> New Tag
<% end %>

app/views/tags/new.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View list', tags_path %></li>
  <li class="active"><%= link_to 'New tag', new_tag_path %></li>
</ul>

<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/thofins/_form.html.erb
<%= form_for(@thofin) do |f| %>
  <% if @thofin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thofin.errors.count, "error") %> prohibited this thofin from being saved:</h2>

      <ul>
      <% @thofin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thofins/edit.html.erb
<h1>Editing Thofin</h1>

<%= render 'form' %>

<%= link_to 'Show', @thofin %> |
<%= link_to 'Back', thofins_path %>

app/views/thofins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Thofins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thofins.each do |thofin| %>
      <tr>
        <td><%= thofin.name %></td>
        <td><%= thofin.description %></td>
        <td><%= link_to 'Show', thofin, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_thofin_path(thofin), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Destroy', thofin, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_thofin_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> New Thofin
<% end %>

app/views/thofins/new.html.erb
<h1>New Thofin</h1>

<%= render 'form' %>

<%= link_to 'Back', thofins_path %>

app/views/thofins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @thofin.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @thofin.description %>
</p>

<%= link_to 'Edit', edit_thofin_path(@thofin) %> |
<%= link_to 'Back', thofins_path %>